from __future__ import annotations

import argparse
from pathlib import Path
import sys


GENERATED_HEADER = "<!-- generated by `themis docs cli --write`; do not edit by hand -->"


def handle_cli_docs(args: argparse.Namespace) -> int:
    content = render_cli_docs()
    path = args.path
    if args.write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return 0
    if args.check:
        try:
            current = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"themis docs error: {path} does not exist", file=sys.stderr)
            return 3
        if current != content:
            print(f"themis docs error: {path} is out of date; run `themis docs cli --write`", file=sys.stderr)
            return 2
        return 0
    print(content)
    return 0


def render_cli_docs() -> str:
    from .cli import build_parser

    parser = build_parser()
    sections = [GENERATED_HEADER, "", "# Themis CLI Reference", ""]
    sections.append("This file is generated from the argparse command tree. Update CLI code first, then run `themis docs cli --write`.")
    sections.append("")
    for command_parser in collect_parsers(parser):
        sections.append(f"## `{command_parser.prog}`")
        sections.append("")
        sections.append("```text")
        sections.append(command_parser.format_help().rstrip())
        sections.append("```")
        sections.append("")
    return "\n".join(sections)


def collect_parsers(parser: argparse.ArgumentParser) -> list[argparse.ArgumentParser]:
    parsers: list[argparse.ArgumentParser] = []
    seen: set[int] = set()

    def visit(current: argparse.ArgumentParser) -> None:
        identifier = id(current)
        if identifier in seen:
            return
        seen.add(identifier)
        parsers.append(current)
        for action in current._actions:
            if isinstance(action, argparse._SubParsersAction):
                for subparser in action.choices.values():
                    visit(subparser)

    visit(parser)
    return parsers


def main() -> int:
    parser = argparse.ArgumentParser(prog="python -m themis.docs")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("-p", "--path", type=Path, default=Path("docs/cli.md"))
    return handle_cli_docs(parser.parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
